[Interface]
PrivateKey = ${CLIENT_PRIVATE_KEY}
Address = ${WG_CLIENT_ADDRESS_V4}, ${WG_CLIENT_ADDRESS_V6}
DNS = ${WG_DNS_ADDRESS_V4}, ${WG_DNS_ADDRESS_V6}

[Peer]
PublicKey = ${SERVER_PUBLIC_KEY}
Endpoint = ${PUBLIC_IPV4}:${WG_LISTEN_PORT}
AllowedIPs = ${WG_CLIENT_ALLOWED_IPS_V4}, ${WG_CLIENT_ALLOWED_IPS_V6}
PersistentKeepalive = ${WG_PEER_PERSISTENT_KEEPALIVE}
