[Interface]
PrivateKey = ${CLIENT_PRIVATE_KEY}
Address = 10.0.0.2/32, fd42:42:42::2/128
DNS = 10.0.0.1, fd42:42:42::1

[Peer]
PublicKey = ${SERVER_PUBLIC_KEY}
Endpoint = ${PUBLIC_IPV4}:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25